#!/bin/bash

time=$(date "+%Y-%m-%d %H:%M:%S")

dpthvHeader="
;FILE_FORMAT=3:3
;TYPE=PLATED
;Layer: PTH_Through_Via
;EasyEDA v6.5.23, ${time}
;Gerber Generator version 0.2
"

dpthHeader="
;FILE_FORMAT=3:3
;TYPE=PLATED
;Layer: PTH_Through
;EasyEDA v6.5.23, ${time}
;Gerber Generator version 0.2
;Holesize 1 = 0.915 mm
"

function genGerber {
    echo "Generating ${1}"
    echo "
G04 Layer: ${1}*
G04 EasyEDA v6.5.23, ${time}*
G04 Gerber Generator version 0.2*
G04 Scale: 100 percent, Rotated: No, Reflected: No *
G04 Dimensions in millimeters *
G04 leading zeros omitted , absolute positions ,4 integer and 5 decimal *
" > Gerber_${1}.${2}
}

echo "KiCad2EasyEDA (Copyleft) Dogecraft@github.com/dogecraft"
echo

if [ -z $1 ]
then
    echo "ERROR: Inner layers is undefined!"
    echo
    echo "Usage: $0 (inner layers)"
    exit
fi

echo "Inner layers: ${1}"
echo

rm -rf output
mkdir output

cd output

genGerber TopLayer GTL
genGerber TopSolderMaskLayer GTS
genGerber BottomLayer GBL
genGerber BottomSolderMaskLayer GBS
genGerber TopSilkscreenLayer GTO
genGerber BottomSilkscreenLayer GBO
genGerber BoardOutlineLayer GKO

for N in $(seq 1 $1)
do
    genGerber InnerLayer${N} G${N}
    cat ../*In${N}_Cu* >> Gerber_InnerLayer${N}.G${N}
    if [ $? != 0 ]
    then
        echo "ERROR: Something went wrong. Make sure the inner layers setting is correct."
        exit
    fi
done

echo "Generating drill files"
echo $dpthHeader > Drill_PTH_Through.DRL
echo $dpthvHeader > Drill_PTH_Through_Via.DRL

cat ../*F_Cu* >> Gerber_TopLayer.GTL
cat ../*F_Mask* >> Gerber_TopSolderMaskLayer.GTS
cat ../*B_Cu* >> Gerber_BottomLayer.GBL
cat ../*B_Mask* >> Gerber_BottomSolderMaskLayer.GBS
cat ../*F_Silk* >> Gerber_TopSilkscreenLayer.GTO
cat ../*B_Silk* >> Gerber_BottomSilkscreenLayer.GBO

cat ../*Edge* >> Gerber_BoardOutlineLayer.GKO
cat ../*NPTH* >> Drill_PTH_Through.DRL
cat ../*-PTH* >> Drill_PTH_Through_Via.DRL

echo "Complete!"
